"""Package state tracking for dots-managed packages.

Records what was last successfully applied from each manifest source so
that removals (items deleted from manifest.toml or uvenv.lock) can be
detected, presented to the user for confirmation, and executed via pyinfra
or uvenv before the next install run.

State file: ~/.local/share/dots/state.toml
Override location with the $DOTS_STATE environment variable.
"""

from __future__ import annotations

import os
import tomllib
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


def state_path() -> Path:
    """Return the path to the state file, respecting $DOTS_STATE."""
    if env := os.environ.get("DOTS_STATE"):
        return Path(env).expanduser().resolve()
    return Path.home() / ".local" / "share" / "dots" / "state.toml"


def _fmt_list(items: list[str]) -> str:
    """Serialize a sorted list of strings as a TOML inline array."""
    if not items:
        return "[]"
    inner = ", ".join(f'"{item}"' for item in sorted(items))
    return f"[{inner}]"


@dataclass
class DotsState:
    """Snapshot of all dots-managed packages at last successful ``dots install``."""

    profile: str = ""
    applied_at: str = ""
    pacman: list[str] = field(default_factory=list)
    aur: list[str] = field(default_factory=list)
    npm_global: list[str] = field(default_factory=list)
    uvenv_tools: list[str] = field(default_factory=list)
    cargo_tools: list[str] = field(default_factory=list)
    go_tools: list[str] = field(default_factory=list)


def load() -> DotsState:
    """Load state from disk; return an empty DotsState if the file does not exist."""
    path = state_path()
    if not path.exists():
        return DotsState()
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return DotsState(
        profile=data.get("meta", {}).get("profile", ""),
        applied_at=data.get("meta", {}).get("applied_at", ""),
        pacman=data.get("packages", {}).get("pacman", []),
        aur=data.get("packages", {}).get("aur", []),
        npm_global=data.get("node", {}).get("global", []),
        uvenv_tools=data.get("uvenv", {}).get("tools", []),
        cargo_tools=data.get("cargo", {}).get("tools", []),
        go_tools=data.get("go", {}).get("tools", []),
    )


def save(state: DotsState, profile: str) -> None:
    """Atomically persist *state* to the state file, creating parent dirs."""
    path = state_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    content = (
        "# Auto-generated by `dots install` — do not edit by hand.\n"
        "\n"
        "[meta]\n"
        f'profile = "{profile}"\n'
        f'applied_at = "{now}"\n'
        "\n"
        "[packages]\n"
        f"pacman = {_fmt_list(state.pacman)}\n"
        f"aur = {_fmt_list(state.aur)}\n"
        "\n"
        "[node]\n"
        f"global = {_fmt_list(state.npm_global)}\n"
        "\n"
        "[uvenv]\n"
        f"tools = {_fmt_list(state.uvenv_tools)}\n"
        "\n"
        "[cargo]\n"
        f"tools = {_fmt_list(state.cargo_tools)}\n"
        "\n"
        "[go]\n"
        f"tools = {_fmt_list(state.go_tools)}\n"
    )
    tmp = path.with_suffix(".toml.tmp")
    tmp.write_text(content)
    tmp.rename(path)
